### ISSUE TITLE
Unable to access windows shares

### ISSUE THREAD

**Issue by danderson2692** [timhaak/docker-plex#44] opened 2016-01-29 05:09 UTC
I believe I'm running into an issue with mounting the shares from the docker-machine running in virtualbox to the docker container. The shares are correctly mounted on the machine (I can ls and see the all of the folders in the directory) but when I try to mount the files, they do not appear in the container.

On top of that, if I do not mount anything to /config I am able to connect to plex and play with plex's settings, however if I mount a valid folder to /config, I am not able to connect to the web service. The folder structure does appear in that mount location on Windows so I have added my windows computer's ip and the vm's ip to allowedNetworks in the preferences file in the share location, but it still does not allow me to connect.

Below is a copy of the plex logs when I try to start it when it is mounted to a valid directory:
```
Jan 29, 2016 03:01:49 [0x7f54413fe700] INFO - Plex Media Server v0.9.14.6.1620-e0b7243 - ubuntu PC x86_64 - build: linux-ubuntu-x86_64 ubuntu
Jan 29, 2016 03:01:49 [0x7f54413fe700] INFO - Linux version: 4.1.13-boot2docker (#1 SMP Fri Nov 20 19:05:50 UTC 2015)
Jan 29, 2016 03:01:49 [0x7f54413fe700] INFO - Processor AMD FX(tm)-6300 Six-Core Processor             
Jan 29, 2016 03:01:49 [0x7f544d1d3800] DEBUG - BPQ: [Idle] -> [Starting]
Jan 29, 2016 03:01:49 [0x7f544d1d3800] DEBUG - Opening 20 database sessions to library, SQLite 3.8.9, threadsafe=1
Jan 29, 2016 03:01:49 [0x7f544d1d3800] ERROR - SQLITE3:0x10, 5386, os_unix.c:29880: (22) mmap(/config/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db-shm) - Invalid argument
Jan 29, 2016 03:01:49 [0x7f544d1d3800] ERROR - SQLITE3:0x10, 5386, disk I/O error
Jan 29, 2016 03:01:49 [0x7f544d1d3800] ERROR - Database corruption: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=4000
Jan 29, 2016 03:01:49 [0x7f544d1d3800] ERROR - Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=4000

```
I believe these errors also point toward issues with the file sharing.
Any ideas on how to solve one or both issues? I'm pretty sure that solving one will solve the other. Any help would be greatly appreciated!

**Comment by timhaak** [comment] 2016-01-29 07:42
Hi 

This isn't a bug with this image but most likely with how you've set up the server/mounting.

Also we would need more info to be able help.

Ie. What commands are you running against docker.

What docker version.

How and where have you mounted the samba share.

I'm also mounting the video folder via a samba share.

Here is my info as an example of the info we'll need to help and possibly you'll see something that differs that will help you.

OS = Ubuntu 15.10
Docker version 1.9.0, build 76d6bc9

Fstab entry to mount the file share

```
//192.168.x.x/share /mnt/share cifs dir_mode=0777,file_mode=0666,gid=115,uid=108,noperm,credentials=/root/.smbcredentials,iocharset=utf8,sec=ntlmv2,nounix 0 0
```

Command to run docker
```
docker run --restart=always -d --net="host" -v /confd/plex/:/config -v /mnt/share:/data -p 32400:32400 --name plex  timhaak/plex
```

**Comment by timhaak** [comment] 2016-02-12 13:58
Ok assuming the problem is solved so closing this.

**Closed by timhaak** 2016-02-12 13:58 UTC
Labels: invalid, wontfix
